### ISSUE TITLE
Create template folder structure, data, results and analysis scripts, and tex file for k-means oversampling in remote sensing paper

### ISSUE THREAD

**Issue by joaopfonseca** [AlgoWit/publications#82]
What should we include in the experiment scripts for an initial commit?

I'm assuming it would be useful to use the oversampling algorithms implemented in the [clover](https://github.com/AlgoWit/cluster-over-sampling) library, along with the well-known state-of-the-art oversampling methods. The remaining parameters should probably be kept similar to the configurations in the G-SMOTE in land cover classification paper, no?

For now I'm just using a real dataset I have in my computer (which sadly is too large to upload it to the repo) and the classical ones configured in the `RemoteSensingDatasets` module from the `utils.py` script

Let me know what should I add/edit to this before opening a PR.

**Comment by georgedouzas** [comment]
First of all,  we need a `template` directory. It should include a skeleton for the tex file and maybe for the scripts.

The clover package supports general clustering based oversampling. I will provide a specialized version of it for the kmeans-smote algorithm. In the mean time you can use clover to get some initial results.

**Comment by joaopfonseca** [comment]
Opened PR #84 ; Adds a template directory and a skeleton for the tex file. As for the experiment, should I start working on it or should I wait until you provide the specialized version for the kmeans-smote algorithm?
